channels:
  - 'conda-forge'
dependencies:
  - python=3.10
  - click
  - gdal
  - pip
  - pydantic
  - pyqt
  - rasterio
  - requests
  - rich
  - scanpy
  - scipy
  - tifffile
  - pip:
      - -e .
      - rich-click
